force-app/main/default/objects/MessageLog__c/MessageLog__c.object-meta.xml
<CustomObject>
    <description>custom object to store inbound and outbound chat messages</description>
    <label>MessageLog</label>
    <nameField>
        <label>MessageLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MessageLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MessageLog__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>field to store the inbound and outbound messgaes.</description>
    <label>Message</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/MessageLog__c/fields/MessageType__c.field-meta.xml
<CustomField>
    <fullName>MessageType__c</fullName>
    <description>field to determine the message</description>
    <label>MessageType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MessageLog__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>to which user the message is</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MessageLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MessageLogEvent__e/MessageLogEvent__e.object-meta.xml
<CustomObject>
    <label>MessageLogEvent</label>
    <pluralLabel>MessageLogEvent</pluralLabel>
</CustomObject>

force-app/main/default/objects/MessageLogEvent__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>inbound / outbound message</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MessageLogEvent__e/fields/MessageType__c.field-meta.xml
<CustomField>
    <fullName>MessageType__c</fullName>
    <label>MessageType</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MessageLogEvent__e/fields/SfdcUser__c.field-meta.xml
<CustomField>
    <fullName>SfdcUser__c</fullName>
    <label>SfdcUser</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PublishMessageUtil.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 08-13-2020
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   08-13-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public without sharing class PublishMessageUtil {

    /**
    * @description 
    * @author ChangeMeIn@UserSettingsUnder.SFDoc | 08-13-2020 
    * @param messageLogList 
    **/
    public static void publishMessages(List<MessageLog__c> messageLogList){

        List<MessageLogEvent__e> messageLogEventList = new List<MessageLogEvent__e>();

        for (MessageLog__c messageLog : messageLogList) {
            MessageLogEvent__e messageLogEvent = new MessageLogEvent__e();
            messageLogEvent.Message__C=messageLog.Message__C;
            messageLogEvent.MessageType__c=messageLog.MessageType__c;
            messageLogEvent.SfdcUser__C=messageLog.User__C;
            messageLogEventList.add(messageLogEvent);
        }                
        // Call method to publish events
        List<Database.SaveResult> results = EventBus.publish(messageLogEventList);        
        // Inspect publishing result for each event
        for (Database.SaveResult sr : results) {
            if (sr.isSuccess()) {
                System.debug('Successfully published event.');
            } else {
                for(Database.Error err : sr.getErrors()) {
                    System.debug('Error returned: ' +
                                err.getStatusCode() +
                                ' - ' +
                                err.getMessage());
                }
            }       
        }
        

    }
    
}